package com.crtb.oss.model;

// Generated Mar 17, 2015 4:56:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TContract generated by hbm2java
 */
@Entity
@Table(name = "t_contract", catalog = "db_oss")
public class TContract implements java.io.Serializable {

	private Integer id;
	private TBid TBid;
	private TLine TLine;
	private String contractNo;
	private String customerName;
	private String customerPhone;
	private Set<TImei> TImeis = new HashSet<TImei>(0);

	public TContract() {
	}

	public TContract(TBid TBid, TLine TLine, String contractNo,
			String customerName, String customerPhone) {
		this.TBid = TBid;
		this.TLine = TLine;
		this.contractNo = contractNo;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
	}

	public TContract(TBid TBid, TLine TLine, String contractNo,
			String customerName, String customerPhone, Set<TImei> TImeis) {
		this.TBid = TBid;
		this.TLine = TLine;
		this.contractNo = contractNo;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.TImeis = TImeis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bidId", nullable = false)
	public TBid getTBid() {
		return this.TBid;
	}

	public void setTBid(TBid TBid) {
		this.TBid = TBid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lineId", nullable = false)
	public TLine getTLine() {
		return this.TLine;
	}

	public void setTLine(TLine TLine) {
		this.TLine = TLine;
	}

	@Column(name = "contractNo", nullable = false, length = 50)
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Column(name = "customerName", nullable = false, length = 50)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customerPhone", nullable = false, length = 20)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TContract")
	public Set<TImei> getTImeis() {
		return this.TImeis;
	}

	public void setTImeis(Set<TImei> TImeis) {
		this.TImeis = TImeis;
	}

}
