package com.crtb.oss.model;

// Generated Mar 17, 2015 4:56:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TImei generated by hbm2java
 */
@Entity
@Table(name = "t_imei", catalog = "db_oss")
public class TImei implements java.io.Serializable {

	private Integer id;
	private TContract TContract;
	private int isOutdate;

	public TImei() {
	}

	public TImei(TContract TContract, int isOutdate) {
		this.TContract = TContract;
		this.isOutdate = isOutdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contractId", nullable = false)
	public TContract getTContract() {
		return this.TContract;
	}

	public void setTContract(TContract TContract) {
		this.TContract = TContract;
	}

	@Column(name = "isOutdate", nullable = false)
	public int getIsOutdate() {
		return this.isOutdate;
	}

	public void setIsOutdate(int isOutdate) {
		this.isOutdate = isOutdate;
	}

}
