package com.crtb.oss.model;

// Generated Mar 17, 2015 4:56:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TVersionlist generated by hbm2java
 */
@Entity
@Table(name = "t_versionlist", catalog = "db_oss")
public class TVersionlist implements java.io.Serializable {

	private Integer id;
	private int versionCode;
	private String versionName;
	private String releasNote;
	private String releaseDate;
	private int mandatoryUpgrade;
	private String lines;

	public TVersionlist() {
	}

	public TVersionlist(int versionCode, String versionName, String releasNote,
			String releaseDate, int mandatoryUpgrade, String lines) {
		this.versionCode = versionCode;
		this.versionName = versionName;
		this.releasNote = releasNote;
		this.releaseDate = releaseDate;
		this.mandatoryUpgrade = mandatoryUpgrade;
		this.lines = lines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "versionCode", nullable = false)
	public int getVersionCode() {
		return this.versionCode;
	}

	public void setVersionCode(int versionCode) {
		this.versionCode = versionCode;
	}

	@Column(name = "versionName", nullable = false, length = 45)
	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	@Column(name = "releasNote", nullable = false, length = 45)
	public String getReleasNote() {
		return this.releasNote;
	}

	public void setReleasNote(String releasNote) {
		this.releasNote = releasNote;
	}

	@Column(name = "releaseDate", nullable = false, length = 45)
	public String getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "mandatoryUpgrade", nullable = false)
	public int getMandatoryUpgrade() {
		return this.mandatoryUpgrade;
	}

	public void setMandatoryUpgrade(int mandatoryUpgrade) {
		this.mandatoryUpgrade = mandatoryUpgrade;
	}

	@Column(name = "lines", nullable = false, length = 100)
	public String getLines() {
		return this.lines;
	}

	public void setLines(String lines) {
		this.lines = lines;
	}

}
