package com.crtb.oss.model;

// Generated Mar 17, 2015 4:56:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TVersionstatus generated by hbm2java
 */
@Entity
@Table(name = "t_versionstatus", catalog = "db_oss")
public class TVersionstatus implements java.io.Serializable {

	private Integer id;
	private String imei;
	private String versionNo;
	private String reportTime;

	public TVersionstatus() {
	}

	public TVersionstatus(String imei, String versionNo, String reportTime) {
		this.imei = imei;
		this.versionNo = versionNo;
		this.reportTime = reportTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "IMEI", nullable = false, length = 45)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "versionNo", nullable = false, length = 45)
	public String getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(String versionNo) {
		this.versionNo = versionNo;
	}

	@Column(name = "reportTime", nullable = false, length = 45)
	public String getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(String reportTime) {
		this.reportTime = reportTime;
	}

}
