package cn.dennishucd.db;

// Generated Mar 7, 2015 4:24:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "db_easyui")
public class Student implements java.io.Serializable {

	private Integer studId;
	private String name;
	private String email;
	private Date dob;

	public Student() {
	}

	public Student(String name, String email) {
		this.name = name;
		this.email = email;
	}

	public Student(String name, String email, Date dob) {
		this.name = name;
		this.email = email;
		this.dob = dob;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "stud_id", unique = true, nullable = false)
	public Integer getStudId() {
		return this.studId;
	}

	public void setStudId(Integer studId) {
		this.studId = studId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

}
